apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: aeyq36ccr-nodejs 
  janus-idp.io/tekton: aeyq36ccr-nodejs
  backstage.io/kubernetes-id: aeyq36ccr-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: aeyq36ccr-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml